version: '3'

services:
  django:
    image:
    environment:
    ports:
      - "8000:8000"
    command:
      - bash
      - -c
      - |
        python manage.py makemigration
        python manage.py migrate
    depends_on:
      - db
    container_name: tpay_test